[package]
name = "lolcat"
version = "1.1.0"
authors = ["Umang Raghuvanshi <u@umangis.me>"]
description = "The good ol' lolcat, now with fearless concurrency."
license = "MIT"
repository = "https://github.com/ur0/lolcat"

[dependencies]
clap = "2.32.0"
# Needed for WASI support
rand = {git = "https://github.com/rust-random/rand"}
getrandom = "0.1.2"
